// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WebAPI1.Models;
//
//    var userModel = UserModel.FromJson(jsonString);

namespace WebAPI1.Models
{
    using Newtonsoft.Json;
    using System.ComponentModel.DataAnnotations;

    public partial class UserModel
    {
        [Required]
        [JsonProperty("KULLANICI_NO")]
        public long KullaniciNo { get; set; }

        [JsonProperty("KULLANICI_KISA_ADI")]
        public string KullaniciKisaAdi { get; set; }

        [JsonProperty("KULLANICI_UZUN_ADI")]
        public string KullaniciUzunAdi { get; set; }

        [JsonProperty("KULLANICI_ADI")]
        public string KullaniciAdi { get; set; }
    }

    public partial class UserModel
    {
        public static UserModel FromJson(string json) => JsonConvert.DeserializeObject<UserModel>(json, WebAPI1.Models.Converter.Settings);
    }

    public static class Serialie
    {
        public static string ToJson(this UserModel self) => JsonConvert.SerializeObject(self, WebAPI1.Models.Converter.Settings);
    }

    
}
